config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :photos
  root "photos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :file_location, PhotoImageUploader
  validates_presence_of :title, :date, :description, :file_location
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, :only => [:show, :edit, :update, :destroy]
  def index
    @photos = Photo.all
  end
  def new 
    @photo = Photo.new

  end
  def create
    @photo = Photo.new(photo_params)
    if @photo.save
      redirect_to photos_url
    else
      render  :action => :new
    end
  end
  

  def update
    
    if@photo.update_attributes(photo_params)
      redirect_to photos_path(@photo)
    else
      render  :action => :edit
    end
  end

  def destroy
    @photo.destroy
    redirect_to photos_url
  end

  private

  def set_photo
    @photo = Photo.find(params[:id])
  end

  def photo_params
    params.require(:photo).permit(:title, :date, :description, :file_location)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoAlbum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/photos/_form.html.erb
<% if @photo.errors.present? %>
  <ul>
    <% @photo.errors.each do |error, message| %>
      <li> <%= "#{error.capitalize} #{message}" %></li>
    <% end %>
  </ul>
<% end %>
<div class="form container">
  <%= form_for @photo do |f| %>
    <div class="form-group">
      <%= f.label :title, "Title" %>
      <%= f.text_field :title ,class: "form-control"%>
    </div>
    <div class="form-group">
      <%= f.label :date, "Date" %>
      <%= f.text_field :date ,class: "form-control"%>
    </div>
    <div class="form-group">
      <%= f.label :description, "Description" %>
      <%= f.text_area :description ,class: "form-control"%>
    </div>
    <div class="form-group">
      <%= f.label :file_location %>
      <%= f.file_field :file_location,class: "form-control" %>
    </div>
    <%= f.submit %>
  <% end %>
</div>

app/views/photos/edit.html.erb
<%= render :partial => "form" %>

app/views/photos/index.html.erb
<table class="table table-striped table-condensed">
 <% @photos.each do |photo| %>
   <tr>
    <td><%= photo.title %></td>
    <td><%= link_to 'Show', photo_path(photo) %></td>
    <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
    <td><%= link_to 'Destroy', photo_path(photo), method: :delete, data:{ confirm: "Are you sure?" } %></td>
   </tr>
 <% end %>
</table>

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<%= render :partial => "form" %>

app/views/photos/show.html.erb
<%= @photo.title %>
<%= @photo.date %>
<%= image_tag @photo.file_location.url,size: "140x140",class: "img-thumbnail" %>
<%= simple_format(@photo.description) %>

<%= link_to "Back to index" , photos_path %>